# The name of the app. Must be unique within a project.
name: app

# The type of the application to build
type: 'python:3.9.9'

# The size of the persistent disk of the application (in MB)
disk: 1024

# Your app's configuration when it's exposed to the web.
web:
    commands:
        start: python app.py

hooks:
    build: pipenv install --system --deploy